-- MySQL Script generated by MySQL Workbench
-- Mon Apr 21 20:57:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema darba_apkopojums
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema darba_apkopojums
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `darba_apkopojums` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `darba_apkopojums` ;

-- -----------------------------------------------------
-- Table `darba_apkopojums`.`stradnieka_apkopojums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `darba_apkopojums`.`stradnieka_apkopojums` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vards_uzvards` VARCHAR(100) NOT NULL,
  `datums` DATE NOT NULL,
  `nostradatas_stundas` DECIMAL(5,2) NOT NULL,
  `padaritais_darbs` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `darba_apkopojums`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `darba_apkopojums`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(255) NOT NULL,
  `is_admin` TINYINT(1) NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `darba_apkopojums`.`uzņemeja_apkopojums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `darba_apkopojums`.`uzņemeja_apkopojums` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vards_uzvards` VARCHAR(100) NOT NULL,
  `izvertejums` ENUM('ļoti slikti', 'slikti', 'viduvēji', 'labi', 'ļoti labi') NOT NULL,
  `alga` DECIMAL(10,2) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
